Repository naneun/sidedish, pull requests merged in 2022-04, with the labels that each got.

#12 [Issue #6] 도메인 클래스 생성 및 swagger 로 API 문서 만들기
  backend/src/main/java/com/terria/sidedish/api/CategoryController.java
  backend/src/main/java/com/terria/sidedish/api/OrderController.java
  backend/src/main/java/com/terria/sidedish/api/SideDishController.java
  backend/src/main/java/com/terria/sidedish/domain/Category.java
  backend/src/main/java/com/terria/sidedish/domain/DiscountEvent.java
  backend/src/main/java/com/terria/sidedish/domain/Division.java
  backend/src/main/java/com/terria/sidedish/domain/Member.java
  backend/src/main/java/com/terria/sidedish/domain/OrderSheet.java
  backend/src/main/java/com/terria/sidedish/domain/Shipping.java
  backend/src/main/java/com/terria/sidedish/domain/SideDish.java
  backend/src/main/java/com/terria/sidedish/domain/SideDishImage.java
Labels: 백엔드, 구조설계

#13 [Issue #9] 물리적 설계
  backend/build.gradle
  backend/src/main/resources/application-dev.properties
  backend/src/main/resources/schema.sql
Labels: 백엔드, 구조설계

#19 [Issue #17] 기획전, 일반 진열 상품 카테고리별 상품 목록 조회 기능 구현
  backend/src/main/java/com/terria/sidedish/api/ExhibitionController.java
  backend/src/main/java/com/terria/sidedish/api/OrderController.java
  backend/src/main/java/com/terria/sidedish/api/SideDishController.java
  backend/src/main/java/com/terria/sidedish/domain/DiscountEvent.java
  backend/src/main/java/com/terria/sidedish/domain/Exhibition.java
  backend/src/main/java/com/terria/sidedish/domain/Shipping.java
  backend/src/main/java/com/terria/sidedish/domain/SideDish.java
  backend/src/main/java/com/terria/sidedish/domain/SideDishImage.java
  backend/src/main/java/com/terria/sidedish/domain/entity/aggregate/Exhibition.java
  backend/src/main/java/com/terria/sidedish/domain/entity/aggregate/OrderSheet.java
  backend/src/main/java/com/terria/sidedish/domain/entity/link/CategoryHasSideDish.java
  backend/src/main/java/com/terria/sidedish/domain/entity/link/SideDishHasDiscountEvent.java
  backend/src/main/java/com/terria/sidedish/domain/entity/reference/Category.java
  backend/src/main/java/com/terria/sidedish/domain/entity/reference/DiscountEvent.java
  backend/src/main/java/com/terria/sidedish/domain/entity/reference/SideDish.java
  backend/src/main/java/com/terria/sidedish/domain/entity/reference/SideDishImage.java
  backend/src/main/java/com/terria/sidedish/dto/response/CategoryResponse.java
  backend/src/main/java/com/terria/sidedish/dto/response/DiscountEventResponse.java
  backend/src/main/java/com/terria/sidedish/dto/response/ExhibitionResponse.java
  backend/src/main/java/com/terria/sidedish/dto/response/SideDishCardResponse.java
  backend/src/main/java/com/terria/sidedish/repository/CategoryRepository.java
  backend/src/main/java/com/terria/sidedish/repository/DiscountEventRepository.java
  backend/src/main/java/com/terria/sidedish/repository/ExhibitionRepository.java
  backend/src/main/java/com/terria/sidedish/repository/SideDishRepository.java
  backend/src/main/java/com/terria/sidedish/service/ExhibitionService.java
  backend/src/main/resources/application-dev.properties
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/terria/sidedish/repository/ExhibitionRepositoryTest.java
  backend/src/test/java/com/terria/sidedish/repository/SideDishRepositoryTest.java
Labels: 백엔드, 기능구현

#22 Fe#15
  fe/src/App.js
  fe/src/components/BestProduct.js
  fe/src/components/BestProduct/TapList.js
  fe/src/components/BestProduct/TapMenu.js
  fe/src/components/Card.js
  fe/src/components/Card.styled.js
  fe/src/components/Header.js
  fe/src/helper/constants.js
  fe/src/helper/mock.js
  fe/src/helper/utils.js
  fe/src/views/BestProduct.js
  fe/src/views/Header.js
  fe/src/views/bestProduct/BestProduct.styled.js
  fe/src/views/bestProduct/tabList.js
  fe/src/views/bestProduct/tabMenu.js
  fe/src/views/header/Header.styled.js
  fe/src/views/header/gnbLists.js
  fe/src/views/header/svg.js
Labels: 프론트엔드, 기능구현, 리펙토링

#23 1주차 1차 리뷰 내용 반영
  backend/build.gradle
  backend/src/main/java/com/terria/sidedish/api/ExhibitionController.java
  backend/src/main/java/com/terria/sidedish/config/DataJdbcConfig.java
  backend/src/main/java/com/terria/sidedish/config/WebMvcConfig.java
  backend/src/main/java/com/terria/sidedish/domain/entity/aggregate/OrderSheet.java
  backend/src/main/java/com/terria/sidedish/error/ErrorCode.java
  backend/src/main/java/com/terria/sidedish/error/ErrorResponse.java
  backend/src/main/java/com/terria/sidedish/error/ExhibitionRunTimeException.java
  backend/src/main/java/com/terria/sidedish/service/ExhibitionService.java
Labels: 백엔드, 기능구현

#27 [Issue #25] 1주차 2차 리뷰 반영
  backend/.gitignore
  backend/src/main/java/com/terria/sidedish/api/ExhibitionController.java
  backend/src/main/java/com/terria/sidedish/dto/response/CategoryResponse.java
  backend/src/main/java/com/terria/sidedish/dto/response/DiscountEventResponse.java
  backend/src/main/java/com/terria/sidedish/dto/response/ExhibitionResponse.java
  backend/src/main/java/com/terria/sidedish/dto/response/SideDishCardResponse.java
  backend/src/main/java/com/terria/sidedish/error/ErrorCode.java
  backend/src/main/java/com/terria/sidedish/error/ErrorResponse.java
  backend/src/main/java/com/terria/sidedish/error/ExhibitionException.java
  backend/src/main/java/com/terria/sidedish/error/HandlerAdvice.java
  backend/src/main/java/com/terria/sidedish/service/ExhibitionService.java
Labels: 백엔드, 리뷰반영

#31 Fe#26
  fe/src/App.js
  fe/src/components/Card.js
  fe/src/components/Card.styled.js
  fe/src/helper/constants.js
  fe/src/helper/mock.js
  fe/src/views/Category.js
  fe/src/views/bestProduct/BestProduct.styled.js
  fe/src/views/bestProduct/tabList.js
  fe/src/views/bestProduct/tabMenu.js
  fe/src/views/header/Header.styled.js
Labels: 프론트엔드, 기능구현

#38 Fe#37
  fe/src/App.js
  fe/src/components/ProductCard.js
  fe/src/components/productCard/ProductCard.js
  fe/src/components/productCard/ProductCard.styled.js
  fe/src/components/productCard/deliveryCircle/deliveryCircle.js
  fe/src/components/productCard/deliveryCircle/deliveryCircle.styled.js
  fe/src/components/productCard/eventWrapper/eventWrapper.js
  fe/src/components/productCard/eventWrapper/eventWrapper.styled.js
  fe/src/views/Category.js
  fe/src/views/header/Header.js
  fe/src/views/header/Header.styled.js
  fe/src/views/header/gnbLists/gnbLists.js
  fe/src/views/header/gnbLists/gnbLists.styled.js
  fe/src/views/header/svg/svg.js
  fe/src/views/header/svg/svg.styled.js
  fe/src/views/main/bestProduct/BestProduct.js
  fe/src/views/main/bestProduct/BestProduct.styled.js
  fe/src/views/main/bestProduct/tabList/tabList.js
  fe/src/views/main/bestProduct/tabList/tabList.styled.js
  fe/src/views/main/bestProduct/tabMenu/tabMenu.js
  fe/src/views/main/bestProduct/tabMenu/tabMenu.styled.js
  fe/src/views/main/bestProduct/title/exhibitionTitle.js
  fe/src/views/main/bestProduct/title/exhibitionTitle.styled.js
  fe/src/views/main/category/Category.js
  fe/src/views/main/category/category.styled.js
Labels: 프론트엔드, 리펙토링, 구조설계

#43 Fe#42
  fe/src/helper/mock.js
  fe/src/helper/mock.json
  fe/src/views/main/categoryArea/category/category.js
  fe/src/views/main/categoryArea/category/category.styled.js
  fe/src/views/main/categoryArea/category/extendBtn.js
Labels: 기능구현

#30 OAuth
  backend/src/main/java/com/terria/sidedish/auth/AuthController.java
  backend/src/main/java/com/terria/sidedish/domain/Member.java
  backend/src/main/java/com/terria/sidedish/domain/entity/aggregate/AccessToken.java
  backend/src/main/java/com/terria/sidedish/dto/auth/GitHubAccessToken.java
  backend/src/main/java/com/terria/sidedish/dto/auth/GitHubUser.java
  backend/src/main/java/com/terria/sidedish/dto/auth/Provider.java
  backend/src/main/java/com/terria/sidedish/dto/response/MemberResponse.java
  backend/src/main/java/com/terria/sidedish/error/ErrorCode.java
  backend/src/main/java/com/terria/sidedish/error/GitHubOAuthException.java
  backend/src/main/java/com/terria/sidedish/error/OAuthException.java
  backend/src/main/java/com/terria/sidedish/repository/DiscountEventRepository.java
  backend/src/main/java/com/terria/sidedish/repository/ExhibitionRepository.java
  backend/src/main/java/com/terria/sidedish/repository/MemberRepository.java
  backend/src/main/java/com/terria/sidedish/repository/SideDishRepository.java
  backend/src/main/java/com/terria/sidedish/service/GitHubAuthService.java
  backend/src/main/resources/schema.sql
Labels: 백엔드, 기능구현

#47 Exhibition Aggregate 분리 작업
  backend/src/main/java/com/terria/sidedish/api/ExhibitionController.java
  backend/src/main/java/com/terria/sidedish/api/SideDishController.java
  backend/src/main/java/com/terria/sidedish/domain/entity/aggregate/Category.java
  backend/src/main/java/com/terria/sidedish/domain/entity/aggregate/Exhibition.java
  backend/src/main/java/com/terria/sidedish/domain/entity/aggregate/SideDish.java
  backend/src/main/java/com/terria/sidedish/dto/response/CategoryResponse.java
  backend/src/main/java/com/terria/sidedish/dto/response/ExhibitionResponse.java
  backend/src/main/java/com/terria/sidedish/dto/response/SideDishCardResponse.java
  backend/src/main/java/com/terria/sidedish/dto/response/SideDishDetailResponse.java
  backend/src/main/java/com/terria/sidedish/repository/ExhibitionRepository.java
  backend/src/main/java/com/terria/sidedish/repository/SideDishRepository.java
  backend/src/main/java/com/terria/sidedish/service/ExhibitionService.java
  backend/src/main/java/com/terria/sidedish/service/SideDishService.java
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/terria/sidedish/repository/SideDishRepositoryTest.java
Labels: 백엔드, 긴급수정

#51 [Issue #48] 주문하기 기능 추가
  backend/src/main/java/com/terria/sidedish/api/OrderSheetController.java
  backend/src/main/java/com/terria/sidedish/domain/entity/aggregate/OrderSheet.java
  backend/src/main/java/com/terria/sidedish/dto/request/OrderSheetRequest.java
  backend/src/main/java/com/terria/sidedish/dto/response/OrderSheetResponse.java
  backend/src/main/java/com/terria/sidedish/dto/response/sidedish/SideDishCardResponses.java
  backend/src/main/java/com/terria/sidedish/repository/OrderSheetRepository.java
  backend/src/main/java/com/terria/sidedish/service/OrderSheetService.java
  backend/src/main/java/com/terria/sidedish/service/SideDishService.java
  backend/src/main/resources/schema.sql
Labels: 백엔드, 기능구현

#53 [fe#50] feat: 수정된 API 기획전 연동
  fe/src/helper/constants.js
  fe/src/views/main/bestProduct/BestProduct.js
Labels: 프론트엔드

#58 2주차 1차 리뷰 내용 반영(리아코)
  backend/src/main/java/com/terria/sidedish/dto/auth/OAuthAdapter.java
  backend/src/main/java/com/terria/sidedish/dto/response/sidedish/SideDishCardResponse.java
  backend/src/main/java/com/terria/sidedish/dto/response/sidedish/SideDishDetailResponse.java
  backend/src/main/java/com/terria/sidedish/error/HandlerAdvice.java
  backend/src/main/java/com/terria/sidedish/error/exception/ExhibitionException.java
  backend/src/main/java/com/terria/sidedish/error/exception/GitHubOAuthException.java
  backend/src/main/java/com/terria/sidedish/error/exception/OAuthException.java
  backend/src/main/java/com/terria/sidedish/error/exception/OrderException.java
  backend/src/main/java/com/terria/sidedish/error/exception/SideDishApplicationException.java
  backend/src/main/java/com/terria/sidedish/error/exception/SideDishException.java
  backend/src/main/java/com/terria/sidedish/service/GitHubAuthService.java
  backend/src/main/java/com/terria/sidedish/service/OrderSheetService.java
  backend/src/main/java/com/terria/sidedish/service/SideDishService.java
  backend/src/main/resources/data.sql
Labels: 백엔드, 리뷰반영

#65 [fe#64] feat: 추천상품 컴포넌트 api 연동 및 클릭이벤트 구현
  fe/src/common/productCard/ProductCard.js
  fe/src/common/productCard/deliveryCircle/deliveryCircle.js
  fe/src/components/main/productDetailModal/productDetailModal.js
  fe/src/components/main/productDetailModal/recommendArea/recommend.styled.js
  fe/src/components/main/productDetailModal/recommendArea/recommendArea.js
Labels: 프론트엔드, 기능구현
